### ISSUE TITLE
Command errored out with exit status 1 - pip install trendet==0.6

### ISSUE THREAD

**Issue by rrfaria** [alvarobartt/trendet#9]
Hi I was analysing your lib
an look like good idea
but I could not install it on my pc or even on google colabs

I tried 
pip install trendet==0.6
and also
pip install trendet --upgrade

On collab:

![image](https://user-images.githubusercontent.com/11916455/82517392-5f9bd500-9af3-11ea-9127-57c2af61fa83.png)

on local:

 line 14, in requirements
        with io.open('requirements.txt', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by rrfaria** [comment]
Solution:
I changed this line on setup.py

![image](https://user-images.githubusercontent.com/11916455/82518977-ef8f4e00-9af6-11ea-8e19-bcec75d4d64a.png)

**Comment by alvarobartt** [comment]
Hi @rrfaria, thanks for reporting this issue! It happens because the `requirements.txt`is not included on the `MANIFEST.in` file, so when installing the package, the requirements is not copied properly. I will fix it as soon as possible so as to release the 0.7 working version. Thank you!

**Comment by alvarobartt** [comment]
I have already solved it, including some other changes I had on the master branch but were not pushed. You can see the changes in: 8692ea99e3c61be80d139030ecf21568cf69ffc9

__Remember to STAR the repo if you found it useful and FOLLOW ME at GitHub so as to get notified of all the updates!__

**Comment by codeofdoug** [comment]
Hi! I am trying to install the trendet on Colab and the same issue from this tread still occurring.

<img width="1215" alt="Screenshot 2020-06-22 at 19 53 54" src="https://user-images.githubusercontent.com/22217599/85319835-70f54a00-b4c2-11ea-9ba5-2ea39cc64850.png">

Is there any perspective for when there will be available the Trendet version 0.7 ?

<img width="1215" alt="Screenshot 2020-06-22 at 19 53 54" src="https://user-images.githubusercontent.com/22217599/85319848-7783c180-b4c2-11ea-9f20-c857111e9671.png">
